name: TinyProtocol
version: 0.0.1-SNAPSHOT
description: Intercept packets without ProtocolLib
author: Comphenix

load: startup

main: com.comphenix.tinyprotocol.ExamplePlugin
database: false

commands:
   toggleinjection:
      description: Toggle the TinyProtocol injection of the current player.
      usage: /<command>